source "https://rubygems.org"

# GitHub Pages compatible setup
gem "github-pages", group: :jekyll_plugins

# For local development with the theme
gem "just-the-docs"
gem "webrick" # Required for Ruby 3.0+
gem "bundler-audit", "0.9.3", require: false
